# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# azure-devops-pipeline.yml
trigger:
- main
- dev

pool:
  name: Default
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  nodeVersion: '18.19.1'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: 'Install Node.js'

    - script: |
        cd src
        npm install
      displayName: 'Install dependencies'

    - script: |
        cd src
        npm run test:coverage
      displayName: 'Run tests with coverage'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/junit.xml'
        mergeTestResults: true
      displayName: 'Publish test results'
      condition: always()

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '**/coverage/cobertura-coverage.xml'
        reportDirectory: '**/coverage/lcov-report'
      displayName: 'Publish code coverage'

    - script: |
        cd src
        npm run build --if-present
      displayName: 'Build application'

    - task: CopyFiles@2
      inputs:
        contents: |
          **/*
          !node_modules/**/*
          !coverage/**/*
          !.git/**/*
        targetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy files to artifact directory'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
      displayName: 'Publish build artifacts'
